In [1]:
import pandas as pd
from datasets import load_dataset

In [2]:
dataset = load_dataset(
    "bitext/Bitext-customer-support-llm-chatbot-training-dataset",
    split = "train"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/11.9k [00:00<?, ?B/s]

d:\Internship Tasks\Task - 2026.08.19\GenAI-Powered-Customer-Support-Assistant-with-RAG\.venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Charith\.cache\huggingface\hub\datasets--bitext--Bitext-customer-support-llm-chatbot-training-dataset. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

Bitext_Sample_Customer_Support_Training_(…): reconstructing file:   0%|          |  0.00B / 19.2MB

Bitext_Sample_Customer_Support_Training_(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/26872 [00:00<?, ? examples/s]

In [3]:
dataset

Dataset({
    features: ['flags', 'instruction', 'category', 'intent', 'response'],
    num_rows: 26872
})

In [5]:
df = dataset.to_pandas()
df.head()

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...

In [6]:
df.to_csv(
    "../data/raw/bitext_customer_support.csv",
    index = False
)

In [7]:
df.shape

(26872, 5)

In [9]:
df.columns

Index(['flags', 'instruction', 'category', 'intent', 'response'], dtype='str')

In [10]:
df.dtypes

flags          str
instruction    str
category       str
intent         str
response       str
dtype: object

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26872 entries, 0 to 26871
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   flags        26872 non-null  str
 1   instruction  26872 non-null  str
 2   category     26872 non-null  str
 3   intent       26872 non-null  str
 4   response     26872 non-null  str
dtypes: str(5)
memory usage: 19.1 MB

In [12]:
df.sample(10)

,flags,instruction,category,intent,response
15862,BEL,I do not know what to do to download my bill #...,INVOICE,get_invoice,"I'm picking up what you're putting down, your ..."
19000,BLM,shop several articles,ORDER,place_order,Thank you for your interest in shopping for se...
5788,BLQ,i need help to see ur available payment methods,PAYMENT,check_payment_methods,Thank you for your message to us for assistanc...
16422,BIL,how can I demand a compensation?,REFUND,get_refund,I realized you would like to know how you can ...
15025,BELQ,i do not know how to download the bill #37777,INVOICE,get_invoice,I've been informed that you're unsure about ho...
19971,BLQ,want help restoring the pin code of my user ac...,ACCOUNT,recover_password,For sure! I understand your need to restore th...
12412,BLM,help me see what shipping methods are there,DELIVERY,delivery_options,"Oh, I completely understand your eagerness to ..."
3347,BLMQ,i dont know how i can check the termination pe...,CANCEL,check_cancellation_fee,No worries! I can help you with that. To check...
5231,BIL,where can I check your payment modalities?,PAYMENT,check_payment_methods,I'm on it! I'm here to guide you on how to acc...
10511,BKL,opening new {{Account Type}} account,ACCOUNT,create_account,Congratulations on deciding to open a new {{Ac...

In [13]:
df.isnull().sum()

flags          0
instruction    0
category       0
intent         0
response       0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [16]:
df["instruction"].duplicated().sum()

np.int64(2237)

In [17]:
df["category"].value_counts()

category
ACCOUNT         5986
ORDER           3988
REFUND          2992
INVOICE         1999
CONTACT         1999
PAYMENT         1998
FEEDBACK        1997
DELIVERY        1994
SHIPPING        1970
SUBSCRIPTION     999
CANCEL           950
Name: count, dtype: int64

In [18]:
df["category"].nunique()

11